import unittest
import CA02.prod.event as Event
import CA02.prod.participant as Participant
import CA02.prod.team as Team

class FullTest(unittest.TestCase):
    
    def test_comprehensive(self):
        partic00A01 = Participant.Participant("Billy Bob Joe Bob John", "Killer", "A", "A")
        self.assertEquals("Billy Bob Joe Bob John", partic00A01.name)
        self.assertEquals("Killer", partic00A01.mount)
        self.assertEquals("A", partic00A01.level)
        self.assertEquals("A", partic00A01.rating)
        self.assertEquals("Billy Bob Joe Bob John", partic00A01.getName())
        self.assertEquals("Killer", partic00A01.getMount())
        self.assertEquals("A", partic00A01.getLevel())
        self.assertEquals("A", partic00A01.getRating())
        self.assertEquals(1, partic00A01.getNumber())
        
        self.assertEquals("Sugar Dumplin", partic00A01.setMount("Sugar Dumplin"))
        self.assertEquals("Sugar Dumplin", partic00A01.getMount())
        self.assertEquals("Herbert", partic00A01.setName("Herbert"))
        self.assertEquals("Herbert", partic00A01.getName())
        self.assertEquals("BN", partic00A01.setLevel("BN"))
        self.assertEquals("BN", partic00A01.getLevel())
        self.assertEquals("B", partic00A01.setRating("B"))
        self.assertEquals("B", partic00A01.getRating())
        self.assertRaises(ValueError, partic00A01.setLevel, "P")
        self.assertRaises(ValueError, partic00A01.setRating, "Q")
        
        partic00B02 = Participant.Participant("Billy Bob Joe Bob John", "Killer", "A")
        self.assertEquals("Billy Bob Joe Bob John", partic00B02.name)
        self.assertEquals("Killer", partic00B02.mount)
        self.assertEquals("A", partic00B02.level)
        self.assertEquals("", partic00B02.rating)
        self.assertEquals("Billy Bob Joe Bob John", partic00B02.getName())
        self.assertEquals("Killer", partic00B02.getMount())
        self.assertEquals("A", partic00B02.getLevel())
        self.assertEquals(None, partic00B02.getRating())
        self.assertEquals(2, partic00B02.getNumber())
        
        partic00B03 = Participant.Participant("Billy Bob Joe Bob John", "Killer")
        self.assertEquals("Billy Bob Joe Bob John", partic00B03.name)
        self.assertEquals("Killer", partic00B03.mount)
        self.assertEquals("", partic00B03.level)
        self.assertEquals("", partic00B03.rating)
        self.assertEquals("Billy Bob Joe Bob John", partic00B03.getName())
        self.assertEquals("Killer", partic00B03.getMount())
        self.assertEquals(None, partic00B03.getLevel())
        self.assertEquals(None, partic00B03.getRating())
        self.assertEquals(3, partic00B03.getNumber())
        
        partic00B04 = Participant.Participant("Billy Bob Joe Bob John")
        self.assertEquals("Billy Bob Joe Bob John", partic00B04.name)
        self.assertEquals("", partic00B04.mount)
        self.assertEquals("", partic00B04.level)
        self.assertEquals("", partic00B04.rating)
        self.assertEquals("Billy Bob Joe Bob John", partic00B04.getName())
        self.assertEquals(None, partic00B04.getMount())
        self.assertEquals(None, partic00B04.getLevel())
        self.assertEquals(None, partic00B04.getRating())
        self.assertEquals(4, partic00B04.getNumber())
        
        partic00B05 = Participant.Participant(name = "Billy Bob Joe Bob John", mount = "Killer", level = "A", rating = "A")
        self.assertEquals("Billy Bob Joe Bob John", partic00B05.name)
        self.assertEquals("Killer", partic00B05.mount)
        self.assertEquals("A", partic00B05.level)
        self.assertEquals("A", partic00B05.rating)
        self.assertEquals("Billy Bob Joe Bob John", partic00B05.getName())
        self.assertEquals("Killer", partic00B05.getMount())
        self.assertEquals("A", partic00B05.getLevel())
        self.assertEquals("A", partic00B05.getRating())
        self.assertEquals(5, partic00B05.getNumber())
        
        partic00B06 = Participant.Participant(name = "Billy Bob Joe Bob John", mount = "Killer", level = "A")
        self.assertEquals("Billy Bob Joe Bob John", partic00B06.name)
        self.assertEquals("Killer", partic00B06.mount)
        self.assertEquals("A", partic00B06.level)
        self.assertEquals("", partic00B06.rating)
        self.assertEquals("Billy Bob Joe Bob John", partic00B06.getName())
        self.assertEquals("Killer", partic00B06.getMount())
        self.assertEquals("A", partic00B06.getLevel())
        self.assertEquals(None, partic00B06.getRating())
        self.assertEquals(6, partic00B06.getNumber())
        
        partic00B07 = Participant.Participant(name = "Billy Bob Joe Bob John", mount = "Killer")
        self.assertEquals("Billy Bob Joe Bob John", partic00B07.name)
        self.assertEquals("Killer", partic00B07.mount)
        self.assertEquals("", partic00B07.level)
        self.assertEquals("", partic00B07.rating)
        self.assertEquals("Billy Bob Joe Bob John", partic00B07.getName())
        self.assertEquals("Killer", partic00B07.getMount())
        self.assertEquals(None, partic00B07.getLevel())
        self.assertEquals(None, partic00B07.getRating())
        self.assertEquals(7, partic00B07.getNumber())
        
        partic00B08 = Participant.Participant(name = "Billy Bob Joe Bob John")
        self.assertEquals("Billy Bob Joe Bob John", partic00B08.name)
        self.assertEquals("", partic00B08.mount)
        self.assertEquals("", partic00B08.level)
        self.assertEquals("", partic00B08.rating)
        self.assertEquals("Billy Bob Joe Bob John", partic00B08.getName())
        self.assertEquals(None, partic00B08.getMount())
        self.assertEquals(None, partic00B08.getLevel())
        self.assertEquals(None, partic00B08.getRating())
        self.assertEquals(8, partic00B08.getNumber())
        
        self.assertRaises(ValueError, Participant.Participant, name = "")
        self.assertRaises(ValueError, Participant.Participant, name = "Herbert", mount = "Sugar Dumplin", level = "Z", rating = "A")
        self.assertRaises(ValueError, Participant.Participant, "Herbert", "Sugar Dumplin", "A", "Z")
        
        particA0009 = Participant.Participant("John Doe-A-Deer")
        particA0010 = Participant.Participant("John Doe-A-Deer")
        particA0011 = Participant.Participant("John Doe-A-Deer")
        particA0012 = Participant.Participant("John Doe-A-Deer")
        particA0013 = Participant.Participant("John Doe-A-Deer")
        particA0014 = Participant.Participant("John Doe-A-Deer")
        particA0015 = Participant.Participant("John Doe-A-Deer")
        particA0016 = Participant.Participant("John Doe-A-Deer")
        particA0017 = Participant.Participant("John Doe-A-Deer")
        particA0018 = Participant.Participant("John Doe-A-Deer")
        particA0019 = Participant.Participant("John Doe-A-Deer")
        particA0020 = Participant.Participant("John Doe-A-Deer")
        particA0021 = Participant.Participant("John Doe-A-Deer")
        particA0022 = Participant.Participant("John Doe-A-Deer")
        particA0023 = Participant.Participant("John Doe-A-Deer")
        particA0024 = Participant.Participant("John Doe-A-Deer")
        particA0025 = Participant.Participant("John Doe-A-Deer")
        particA0026 = Participant.Participant("John Doe-A-Deer")
        particA0027 = Participant.Participant("John Doe-A-Deer")
        particA0028 = Participant.Participant("John Doe-A-Deer")
        particA0029 = Participant.Participant("John Doe-A-Deer")
        particA0030 = Participant.Participant("John Doe-A-Deer")
        particA0031 = Participant.Participant("John Doe-A-Deer")
        particA0032 = Participant.Participant("John Doe-A-Deer")
        particA0033 = Participant.Participant("John Doe-A-Deer")
        particA0034 = Participant.Participant("John Doe-A-Deer")
        particA0035 = Participant.Participant("John Doe-A-Deer")
        particA0036 = Participant.Participant("John Doe-A-Deer")
        particA0037 = Participant.Participant("John Doe-A-Deer")
        particA0038 = Participant.Participant("John Doe-A-Deer")
        particA0039 = Participant.Participant("John Doe-A-Deer")
        particA0040 = Participant.Participant("John Doe-A-Deer")
        particA0041 = Participant.Participant("John Doe-A-Deer")
        particA0042 = Participant.Participant("John Doe-A-Deer")
        particA0043 = Participant.Participant("John Doe-A-Deer")
        particA0044 = Participant.Participant("John Doe-A-Deer")
        particA0045 = Participant.Participant("John Doe-A-Deer")
        particA0046 = Participant.Participant("John Doe-A-Deer")
        particA0047 = Participant.Participant("John Doe-A-Deer")
        particA0048 = Participant.Participant("John Doe-A-Deer")
        particA0049 = Participant.Participant("John Doe-A-Deer")
        particA0050 = Participant.Participant("John Doe-A-Deer")
        particA0051 = Participant.Participant("John Doe-A-Deer")
        particA0052 = Participant.Participant("John Doe-A-Deer")
        particA0053 = Participant.Participant("John Doe-A-Deer")
        particA0054 = Participant.Participant("John Doe-A-Deer")
        particA0055 = Participant.Participant("John Doe-A-Deer")
        particA0056 = Participant.Participant("John Doe-A-Deer")
        particA0057 = Participant.Participant("John Doe-A-Deer")
        particA0058 = Participant.Participant("John Doe-A-Deer")
        particA0059 = Participant.Participant("John Doe-A-Deer")
        particA0060 = Participant.Participant("John Doe-A-Deer")
        particA0061 = Participant.Participant("John Doe-A-Deer")
        particA0062 = Participant.Participant("John Doe-A-Deer")
        particA0063 = Participant.Participant("John Doe-A-Deer")
        particA0064 = Participant.Participant("John Doe-A-Deer")
        particA0065 = Participant.Participant("John Doe-A-Deer")
        particA0066 = Participant.Participant("John Doe-A-Deer")
        particA0067 = Participant.Participant("John Doe-A-Deer")
        particA0068 = Participant.Participant("John Doe-A-Deer")
        particA0069 = Participant.Participant("John Doe-A-Deer")
        particA0070 = Participant.Participant("John Doe-A-Deer")
        particA0071 = Participant.Participant("John Doe-A-Deer")
        particA0072 = Participant.Participant("John Doe-A-Deer")
        particA0073 = Participant.Participant("John Doe-A-Deer")
        particA0074 = Participant.Participant("John Doe-A-Deer")
        particA0075 = Participant.Participant("John Doe-A-Deer")
        particA0076 = Participant.Participant("John Doe-A-Deer")
        particA0077 = Participant.Participant("John Doe-A-Deer")
        particA0078 = Participant.Participant("John Doe-A-Deer")
        particA0079 = Participant.Participant("John Doe-A-Deer")
        particA0080 = Participant.Participant("John Doe-A-Deer")
        particA0081 = Participant.Participant("John Doe-A-Deer")
        particA0082 = Participant.Participant("John Doe-A-Deer")
        particA0083 = Participant.Participant("John Doe-A-Deer")
        particA0084 = Participant.Participant("John Doe-A-Deer")
        particA0085 = Participant.Participant("John Doe-A-Deer")
        particA0086 = Participant.Participant("John Doe-A-Deer")
        particA0087 = Participant.Participant("John Doe-A-Deer")
        particA0088 = Participant.Participant("John Doe-A-Deer")
        particA0089 = Participant.Participant("John Doe-A-Deer")
        particA0090 = Participant.Participant("John Doe-A-Deer")
        particA0091 = Participant.Participant("John Doe-A-Deer")
        particA0092 = Participant.Participant("John Doe-A-Deer")
        particA0093 = Participant.Participant("John Doe-A-Deer")
        particA0094 = Participant.Participant("John Doe-A-Deer")
        particA0095 = Participant.Participant("John Doe-A-Deer")
        particA0096 = Participant.Participant("John Doe-A-Deer")
        particA0097 = Participant.Participant("John Doe-A-Deer")
        particA0098 = Participant.Participant("John Doe-A-Deer")
        particA0099 = Participant.Participant("John Doe-A-Deer")
        
        self.assertRaises(ValueError, Participant.Participant, name = "Bob")
               
    #def test02CreateTeam(self):
        test02Instance01 = Team.Team("Lightning")
        test02InstanceA1 = Team.Team("Thunder")
        self.assertEquals("Lightning", test02Instance01.name)
        self.assertEquals("Lightning", test02Instance01.getName())
        self.assertEquals(1, test02Instance01.getNumber())
        
        self.assertRaises(ValueError, Team.Team, "")
        self.assertEquals(1, test02Instance01.addParticipant(partic00A01))
        self.assertEquals(2, test02Instance01.addParticipant(partic00B02))
        
        self.assertEquals(True, partic00A01.queryIsInTeam())
        
        self.assertRaises(ValueError, test02InstanceA1.addParticipant, partic00A01)
        self.assertRaises(ValueError, test02Instance01.addParticipant, None)
        self.assertEquals(3, test02Instance01.addParticipant(partic00B03))
        self.assertRaises(ValueError, test02Instance01.addParticipant, partic00B03)
        self.assertEquals(4, test02Instance01.addParticipant(partic00B04))
        self.assertRaises(ValueError, test02Instance01.addParticipant, partic00B05)
        self.assertRaises(ValueError, test02Instance01.getParticipant, 5)
        self.assertEquals(partic00A01, test02Instance01.getParticipant(1))
        self.assertEquals(partic00B02, test02Instance01.getParticipant(2))
        self.assertEquals(partic00B03, test02Instance01.getParticipant(3))
        self.assertEquals(partic00B04, test02Instance01.getParticipant(4))
        self.assertEquals(None, test02Instance01.getStableManager())
        self.assertEquals(None, test02Instance01.getCaptain())
        self.assertEquals(2, test02Instance01.designateCaptain(2))
        self.assertEquals(3, test02Instance01.designateStableManager(3))
        self.assertEquals(3, test02Instance01.getStableManager())
        self.assertEquals(2, test02Instance01.getCaptain())
        self.assertRaises(ValueError, test02Instance01.designateCaptain, 100)
        self.assertRaises(ValueError, test02Instance01.designateStableManager, 50)
        self.assertEquals(2, test02Instance01.removeParticipant(2))
        self.assertEquals(3, test02Instance01.removeParticipant(3))
        self.assertEquals(4, test02Instance01.removeParticipant(4))
        self.assertEquals(1, test02Instance01.removeParticipant(1))
        self.assertEquals(test02Instance01.participants, test02Instance01.getRoster())
        self.assertRaises(ValueError, test02Instance01.removeParticipant, 5)
        self.assertRaises(ValueError, test02Instance01.removeParticipant, 7)
        self.assertEquals(None, test02Instance01.getStableManager())
        self.assertEquals(None, test02Instance01.getCaptain())
        self.assertEquals(1, test02Instance01.addParticipant(partic00A01))
        self.assertEquals(2, test02Instance01.addParticipant(partic00B02))
        self.assertEquals(4, test02Instance01.addParticipant(partic00B04))
        self.assertEquals(3, test02Instance01.addParticipant(partic00B03))
        self.assertRaises(ValueError, test02Instance01.addParticipant, partic00B05)
        self.assertEquals(test02Instance01.participants, test02Instance01.getRoster())
        
        
        #MAKE MORE THAN 20 TEAMS
        test02Instance02 = Team.Team("Cake")
        test02Instance03 = Team.Team("Pie")
        test02Instance04 = Team.Team("Crepe")
        test02Instance05 = Team.Team("Pancake")
        test02Instance06 = Team.Team("Apples")
        test02Instance07 = Team.Team("Cherries")
        test02Instance08 = Team.Team("Vanilla Coca-Cola")
        test02Instance09 = Team.Team("Diet Dr. Pepper")
        test02Instance10 = Team.Team("Root beer")
        test02Instance11 = Team.Team("Water")
        test02Instance12 = Team.Team("Power")
        self.assertEquals(12, test02Instance12.getNumber())
        test02Instance13 = Team.Team("Earth")
        test02Instance14 = Team.Team("Fire")
        test02Instance15 = Team.Team("Arm")
        test02Instance16 = Team.Team("Leg")
        teamR01 = Team.Team("One late run")
        teamT01 = Team.Team("Early by 1")
        teamT02 = Team.Team("Sleep to 2")
        
        self.assertRaises(ValueError, Team.Team, "Sugiru!")
        
        
    #def test03CreateEvent(self):
        test03Instance02 = Event.Event("Horse Race")
        self.assertEquals("Horse Race", test03Instance02.getName())
        self.assertRaises(ValueError, Event.Event, "")
        self.assertEquals(1, test03Instance02.addTeam(test02Instance12))
        self.assertEquals(0, test03Instance02.removeTeam(12))
        
        self.assertRaises(ValueError, Event.Event, "")
        eventULM = Event.Event("Ultra Long Marathon")
        self.assertRaises(ValueError, eventULM.addTeam, None)
        
        
        self.assertEquals(1, eventULM.addTeam(teamR01))
        self.assertEquals(0, eventULM.removeTeam(17))
        self.assertEquals(0, eventULM.getTeamCount())
        
        self.assertEquals(1, eventULM.addTeam(teamR01))
        self.assertEquals(2, eventULM.addTeam(teamT01))
        self.assertEquals(3, eventULM.addTeam(test02Instance01))
        
        self.assertEquals("Ultra Long Marathon", eventULM.getName())
        self.assertEquals(3, eventULM.getTeamCount())
        self.assertEquals(teamR01, eventULM.getTeamByNumber(number=17))
        self.assertRaises(ValueError, eventULM.getTeamByNumber, number=1001)
        self.assertRaises(ValueError, eventULM.getTeamByParticipant, number = 5354)
        self.assertEquals(test02Instance01, eventULM.getTeamByParticipant(number = 2))
        
        self.assertRaises(ValueError, eventULM.addTeam, test02Instance01)
        
        self.assertRaises(ValueError, Team.Team, "Final Team Should Fail")
        
        